<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ContactMap.php");

/**
 * ContactDAO provides object-oriented access to the contact table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ContactDAO extends Phreezable
{
	/** @var int */
	public $Idcontact;

	/** @var int */
	public $Institution;

	/** @var int */
	public $Iditem;

	/** @var string */
	public $Idexposition;

	/** @var string */
	public $Idholder;

	/** @var int */
	public $Idcreator;

	/** @var int */
	public $User;

	/** @var string */
	public $Contactname;

	/** @var string */
	public $Urla;

	/** @var string */
	public $Contactcall;

	/** @var string */
	public $Company;

	/** @var string */
	public $Uri;

	/** @var string */
	public $Identity;

	/** @var string */
	public $Federaltaxcode;

	/** @var string */
	public $Statetaxcode;

	/** @var string */
	public $Countytaxcode;


	/**
	 * Returns a dataset of Address objects with matching Contact
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetAddresss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_address_contact1", $criteria);
	}

	/**
	 * Returns a dataset of CreatorContact objects with matching Contact
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCreatorContacts($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_creatorcontact_contact", $criteria);
	}

	/**
	 * Returns a dataset of ExpositionPlacelocation objects with matching Contact
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetExpositionPlacelocations($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_anby2ek1hm7l0n2v7s11ajdmj", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Idcreator
	 * @return Creator
	 */
	public function GetIdCreator()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_contact_creator1");
	}

	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_contact_institution1");
	}

	/**
	 * Returns the foreign object based on the value of User
	 * @return User
	 */
	public function GetUser()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_contact_user");
	}


}
?>