<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CountryMap.php");

/**
 * CountryDAO provides object-oriented access to the country table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CountryDAO extends Phreezable
{
	/** @var int */
	public $Idcountry;

	/** @var string */
	public $Country;

	/** @var string */
	public $Countrycode;


	/**
	 * Returns a dataset of PlaceLocation objects with matching Country
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetPlaceLocations($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_placelocation_country", $criteria);
	}

	/**
	 * Returns a dataset of State objects with matching Country
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetStates($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_state_country1", $criteria);
	}


}
?>