<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CreatornameMap.php");

/**
 * CreatornameDAO provides object-oriented access to the creatorname table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CreatornameDAO extends Phreezable
{
	/** @var int */
	public $Idcreatorname;

	/** @var int */
	public $Creator;

	/** @var string */
	public $Naname;

	/** @var string */
	public $Type;


	/**
	 * Returns the foreign object based on the value of Creator
	 * @return Creator
	 */
	public function GetCreator()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_creatorname_creator");
	}


}
?>