<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CreatorAwardHonourMap.php");

/**
 * CreatorAwardHonourDAO provides object-oriented access to the creator_award_honour table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CreatorAwardHonourDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Description;

	/** @var string */
	public $Grantedby;

	/** @var string */
	public $Title;

	/** @var string */
	public $Type;



}
?>