<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ExpositionReferenceMap.php");

/**
 * ExpositionReferenceDAO provides object-oriented access to the exposition_reference table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ExpositionReferenceDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Type;

	/** @var int */
	public $Exposition;

	/** @var int */
	public $Reference;


	/**
	 * Returns the foreign object based on the value of Exposition
	 * @return Exposition
	 */
	public function GetExposition()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_1v8ywvb944diagioy8oulgjfi");
	}

	/**
	 * Returns the foreign object based on the value of Reference
	 * @return Nreference
	 */
	public function GetReferenceNreference()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_bn9yeqjkv398d64fdibt6jbys");
	}


}
?>