<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ExpositionPlacelocationMap.php");

/**
 * ExpositionPlacelocationDAO provides object-oriented access to the exposition_placelocation table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ExpositionPlacelocationDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Type;

	/** @var int */
	public $Contact;

	/** @var int */
	public $Placelocation;

	/** @var int */
	public $Exposition;


	/**
	 * Returns the foreign object based on the value of Contact
	 * @return Contact
	 */
	public function GetContact()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_anby2ek1hm7l0n2v7s11ajdmj");
	}

	/**
	 * Returns the foreign object based on the value of Exposition
	 * @return Exposition
	 */
	public function GetExposition()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_eidy94mayop8hv1jwy5rjt3p7");
	}

	/**
	 * Returns the foreign object based on the value of Placelocation
	 * @return PlaceLocation
	 */
	public function GetPlacelocationPlaceLocation()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_k75vo2tl0yd87up64gkti5kpf");
	}


}
?>