<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ExpositionDimensionMap.php");

/**
 * ExpositionDimensionDAO provides object-oriented access to the exposition_dimension table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ExpositionDimensionDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Type;

	/** @var int */
	public $Dimension;

	/** @var int */
	public $Exposition;


	/**
	 * Returns the foreign object based on the value of Dimension
	 * @return Dimension
	 */
	public function GetDimension()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_69we0kulo49s1sr97htshsxtw");
	}

	/**
	 * Returns the foreign object based on the value of Exposition
	 * @return Exposition
	 */
	public function GetExposition()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_ai09pidrxa780uxmakwlex92c");
	}


}
?>