<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("FondLevelMap.php");

/**
 * FondLevelDAO provides object-oriented access to the fond_level table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class FondLevelDAO extends Phreezable
{
	/** @var int */
	public $Idfondlevel;

	/** @var int */
	public $FondIdfond;

	/** @var int */
	public $LevelsIdlevel;


	/**
	 * Returns the foreign object based on the value of LevelsIdlevel
	 * @return Level
	 */
	public function GetSLevel()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_fondlevel_level");
	}

	/**
	 * Returns the foreign object based on the value of FondIdfond
	 * @return Fond
	 */
	public function GetFond()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_fondlevel_fond");
	}


}
?>