<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("HolderMap.php");

/**
 * HolderDAO provides object-oriented access to the holder table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class HolderDAO extends Phreezable
{
	/** @var int */
	public $Idholder;

	/** @var int */
	public $Institution;

	/** @var string */
	public $Holder;

	/** @var string */
	public $Notes;


	/**
	 * Returns a dataset of Item objects with matching Holder
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetItems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_item_holder1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_holder_institution1");
	}


}
?>