<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ItemdescriptionMap.php");

/**
 * ItemdescriptionDAO provides object-oriented access to the itemdescription table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ItemdescriptionDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $Item;

	/** @var string */
	public $Abstracttext;

	/** @var string */
	public $Accrual;

	/** @var string */
	public $Appraisaldesstructionschedulling;

	/** @var string */
	public $Arrangement;

	/** @var string */
	public $Broadcastmethod;

	/** @var string */
	public $Era;

	/** @var string */
	public $Fromcorporate;

	/** @var string */
	public $Frompersonal;

	/** @var string */
	public $Geographiccoodnates;

	/** @var string */
	public $Geographicname;

	/** @var string */
	public $Label;

	/** @var string */
	public $Language;

	/** @var string */
	public $Mediapresentation;

	/** @var string */
	public $Movement;

	/** @var string */
	public $Other;

	/** @var string */
	public $Period;

	/** @var string */
	public $Periodicity;

	/** @var string */
	public $Preservationstatus;

	/** @var string */
	public $Scope;

	/** @var string */
	public $Style;

	/** @var string */
	public $Subject;

	/** @var string */
	public $Tableofcontents;

	/** @var string */
	public $Targetaudience;

	/** @var string */
	public $Tocorporate;

	/** @var string */
	public $Topersonal;


	/**
	 * Returns the foreign object based on the value of Item
	 * @return Item
	 */
	public function GetItem()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_itemdescription_item");
	}


}
?>