<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("LevelMap.php");

/**
 * LevelDAO provides object-oriented access to the level table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class LevelDAO extends Phreezable
{
	/** @var int */
	public $Idlevel;

	/** @var int */
	public $Fond;

	/** @var int */
	public $Institution;

	/** @var string */
	public $Type;

	/** @var string */
	public $Level;

	/** @var int */
	public $Countitem;

	/** @var string */
	public $Levelcol;


	/**
	 * Returns a dataset of FondLevel objects with matching LevelsIdlevel
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetSFondLevels($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_fondlevel_level", $criteria);
	}

	/**
	 * Returns a dataset of Item objects with matching Level
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetItems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_item_level", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Fond
	 * @return Fond
	 */
	public function GetFond()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_serie_fond1");
	}

	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_serie_institution1");
	}


}
?>