<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("NreferenceMap.php");

/**
 * NreferenceDAO provides object-oriented access to the nreference table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class NreferenceDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Author;

	/** @var string */
	public $Description;

	/** @var string */
	public $OtherInformation;

	/** @var string */
	public $Text;

	/** @var string */
	public $Title;

	/** @var int */
	public $Institution;


	/**
	 * Returns a dataset of CreatorReference objects with matching Reference
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetReferenceCreatorReferences($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_r7ovmckudaqk0px6wtotfyy8c", $criteria);
	}

	/**
	 * Returns a dataset of ExpositionReference objects with matching Reference
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetReferenceExpositionReferences($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_bn9yeqjkv398d64fdibt6jbys", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_360fxrl1q9vf3b3yu70b0lxl1");
	}


}
?>