<?php
/** @package Digital::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ReferenceMediaMap.php");

/**
 * ReferenceMediaDAO provides object-oriented access to the reference_media table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Digital::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ReferenceMediaDAO extends Phreezable
{
	/** @var int */
	public $IdRefMedia;

	/** @var int */
	public $ReferenceIdreference;

	/** @var int */
	public $MediasIdmedia;


	/**
	 * Returns the foreign object based on the value of ReferenceIdreference
	 * @return Reference
	 */
	public function GetReference()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_refmedia_ref");
	}

	/**
	 * Returns the foreign object based on the value of MediasIdmedia
	 * @return Media
	 */
	public function GetSMedia()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_refmedia_media");
	}


}
?>